.alert {
	padding: 15px;
	margin-bottom: 20px;
	border: 1px solid transparent;
	border-radius: 4px;
}

.alert-danger {
	color: #a94442;
	background-color: #f2dede;
	border-color: #ebccd1;
}

.alert-warning {
	color: #8a6d3b;
	/*background-color: #fcf8e3;*/
	background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABsAAAAoCAYAAAAPOoFWAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAPZJREFUeNq81tsOgjAMANB2ov7/7ypaN7IlIwi9rGuT8QSc9EIDAsAznxvY4pXPKr05RUE5MEVB+TyWfCEl9LZApYopCmo9C4FKSMtYoI8Bwv79aQJU4l6hXXCZrQbokJEksxHo9KMOgc6w1atHXM8K9DVC7FQnJ0i8iK3QooGgbnyKgMDygBWyYFZoqx4qS27KqLZJjA1D0jK6QJcYEQEiWv9PGkTsbqxQ8oT+ZtZB6AkdsJnQDnMoHXHLGKOgDYuCWmYhEERCI5gaamW0bnHdA3k2ltlIN+2qKRyCND0bhqSYCyTB3CAOc4WusBEIpkeBuPgJMAAX8Hs1NfqHRgAAAABJRU5ErkJggg==) 0% 0% repeat-x scroll rgb(255, 234, 168) !important;
	border-color: #faebcc;
}

.custom-btn {
	display: inline-block !important;
	padding: 6px 12px !important; 
	margin-bottom: 0 !important;
	font-size: 14px !important;
	font-weight: 400 !important;
	line-height: 1.42857143 !important;
	text-align: center !important;
	white-space: nowrap !important;
	vertical-align: middle !important;
	cursor: pointer !important;
	-webkit-user-select: none !important;
	-moz-user-select: none !important;
	-ms-user-select: none !important;
	user-select: none !important;
	background-image: none !important;
	border: 1px solid transparent !important;
	border-radius: 4px !important;
}

.btn-primary {
	color: #fff !important;
	background-color: #428bca !important;
	border-color: #357ebd !important;
}

.well-sm {
	padding: 5px !important;
	border-radius: 3px !important;
} 

.well {
	min-height: 20px;
	padding: 19px;
	margin-bottom: 20px;
	background-color: #f5f5f5;
	border: 1px solid #e3e3e3;
	border-radius: 4px;
	-webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.05);
	box-shadow: inset 0 1px 1px rgba(0,0,0,.05);
}

.button-blue1 {
	-moz-box-shadow:inset 0px 1px 0px 0px #54a3f7 !important;
	-webkit-box-shadow:inset 0px 1px 0px 0px #54a3f7 !important;
	box-shadow:inset 0px 1px 0px 0px #54a3f7 !important;
	background:-webkit-gradient(linear, left top, left bottom, color-stop(0.05, #007dc1), color-stop(1, #0061a7)) !important;
	background:-moz-linear-gradient(top, #007dc1 5%, #0061a7 100%) !important;
	background:-webkit-linear-gradient(top, #007dc1 5%, #0061a7 100%) !important;
	background:-o-linear-gradient(top, #007dc1 5%, #0061a7 100%) !important;
	background:-ms-linear-gradient(top, #007dc1 5%, #0061a7 100%) !important;
	background:linear-gradient(to bottom, #007dc1 5%, #0061a7 100%) !important;
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#007dc1', endColorstr='#0061a7',GradientType=0) !important;
	background-color:#007dc1 !important;
	-moz-border-radius:3px !important;
	-webkit-border-radius:3px !important;
	border-radius:3px !important; 
	border:1px solid #124d77 !important;
	display:inline-block !important;
	cursor:pointer !important;
	color:#ffffff !important;
	font-family:arial !important;
	font-size:13px !important;
	padding:5px 10px !important;
	text-decoration:none !important;
	text-shadow:0px 1px 0px #154682 !important;
}

.button-blue1:hover {
	background:-webkit-gradient(linear, left top, left bottom, color-stop(0.05, #0061a7), color-stop(1, #007dc1)) !important;
	background:-moz-linear-gradient(top, #0061a7 5%, #007dc1 100%) !important;
	background:-webkit-linear-gradient(top, #0061a7 5%, #007dc1 100%) !important;
	background:-o-linear-gradient(top, #0061a7 5%, #007dc1 100%) !important;
	background:-ms-linear-gradient(top, #0061a7 5%, #007dc1 100%) !important;
	background:linear-gradient(to bottom, #0061a7 5%, #007dc1 100%) !important;
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#0061a7', endColorstr='#007dc1',GradientType=0) !important;
	background-color:#0061a7 !important;
}
.button-blue1:active {
	position:relative !important;
	top:1px !important;
}

.button-orange1 {
	-moz-box-shadow:inset 0px 1px 0px 0px #803c0e !important;
	-webkit-box-shadow:inset 0px 1px 0px 0px #803c0e !important;
	box-shadow:inset 0px 1px 0px 0px #803c0e !important;
	background:-webkit-gradient(linear, left top, left bottom, color-stop(0.05, #bd4200), color-stop(1, #fa6e2d)) !important;
	background:-moz-linear-gradient(top, #bd4200 5%, #fa6e2d 100%) !important;
	background:-webkit-linear-gradient(top, #bd4200 5%, #fa6e2d 100%) !important;
	background:-o-linear-gradient(top, #bd4200 5%, #fa6e2d 100%) !important;
	background:-ms-linear-gradient(top, #bd4200 5%, #fa6e2d 100%) !important;
	background:linear-gradient(to bottom, #bd4200 5%, #fa6e2d 100%) !important;
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#bd4200', endColorstr='#fa6e2d',GradientType=0) !important;
	background-color:#bd4200 !important;
	-moz-border-radius:3px !important;
	-webkit-border-radius:3px !important;
	border-radius:3px !important;
	border:1px solid #733213 !important;
	display:inline-block !important;
	cursor:pointer !important;
	color:#ffffff !important;
	font-family:arial !important;
	font-size:13px !important;
	padding:5px 10px !important;
	text-decoration:none !important;
	text-shadow:0px 1px 0px #154682 !important;
}
.button-orange1:hover {
	background:-webkit-gradient(linear, left top, left bottom, color-stop(0.05, #fa6e2d), color-stop(1, #bd4200)) !important;
	background:-moz-linear-gradient(top, #fa6e2d 5%, #bd4200 100%) !important;
	background:-webkit-linear-gradient(top, #fa6e2d 5%, #bd4200 100%) !important;
	background:-o-linear-gradient(top, #fa6e2d 5%, #bd4200 100%) !important;
	background:-ms-linear-gradient(top, #fa6e2d 5%, #bd4200 100%) !important;
	background:linear-gradient(to bottom, #fa6e2d 5%, #bd4200 100%) !important;
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#fa6e2d', endColorstr='#bd4200',GradientType=0) !important;
	background-color:#fa6e2d !important;
}
.button-orange1:active {
	position:relative !important;
	top:1px !important;
}

.button-red1 {
	-moz-box-shadow:inset 0px 1px 0px 0px #f5565d !important;
	-webkit-box-shadow:inset 0px 1px 0px 0px #f5565d !important;
	box-shadow:inset 0px 1px 0px 0px #f5565d !important;
	background:-webkit-gradient(linear, left top, left bottom, color-stop(0.05, #bf0000), color-stop(1, #a60000)) !important;
	background:-moz-linear-gradient(top, #bf0000 5%, #a60000 100%) !important;
	background:-webkit-linear-gradient(top, #bf0000 5%, #a60000 100%) !important;
	background:-o-linear-gradient(top, #bf0000 5%, #a60000 100%) !important;
	background:-ms-linear-gradient(top, #bf0000 5%, #a60000 100%) !important;
	background:linear-gradient(to bottom, #bf0000 5%, #a60000 100%) !important;
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#bf0000', endColorstr='#a60000',GradientType=0) !important;
	background-color:#bf0000 !important;
	-moz-border-radius:3px !important;
	-webkit-border-radius:3px !important;
	border-radius:3px !important;
	border:1px solid #751313 !important;
	display:inline-block !important;
	cursor:pointer !important;
	color:#ffffff !important;
	font-family:arial !important;
	font-size:13px !important;
	padding:5px 10px !important;
	text-decoration:none !important;
	text-shadow:0px 1px 0px #780c0c !important;
}
.button-red1:hover {
	background:-webkit-gradient(linear, left top, left bottom, color-stop(0.05, #a60000), color-stop(1, #bf0000)) !important;
	background:-moz-linear-gradient(top, #a60000 5%, #bf0000 100%) !important;
	background:-webkit-linear-gradient(top, #a60000 5%, #bf0000 100%) !important;
	background:-o-linear-gradient(top, #a60000 5%, #bf0000 100%) !important;
	background:-ms-linear-gradient(top, #a60000 5%, #bf0000 100%) !important;
	background:linear-gradient(to bottom, #a60000 5%, #bf0000 100%) !important;
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#a60000', endColorstr='#bf0000',GradientType=0) !important;
	background-color:#a60000 !important;
}
.button-red1:active {
	position:relative !important;
	top:1px !important;
}

.button-green1 {
	-moz-box-shadow:inset 0px 1px 0px 0px #acf558 !important;
	-webkit-box-shadow:inset 0px 1px 0px 0px #acf558 !important;
	box-shadow:inset 0px 1px 0px 0px #acf558 !important;
	background:-webkit-gradient(linear, left top, left bottom, color-stop(0.05, #36bd00), color-stop(1, #50a600)) !important;
	background:-moz-linear-gradient(top, #36bd00 5%, #50a600 100%) !important;
	background:-webkit-linear-gradient(top, #36bd00 5%, #50a600 100%) !important;
	background:-o-linear-gradient(top, #36bd00 5%, #50a600 100%) !important;
	background:-ms-linear-gradient(top, #36bd00 5%, #50a600 100%) !important;
	background:linear-gradient(to bottom, #36bd00 5%, #50a600 100%) !important;
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#36bd00', endColorstr='#50a600',GradientType=0) !important;
	background-color:#36bd00 !important;
	-moz-border-radius:3px !important;
	-webkit-border-radius:3px !important;
	border-radius:3px !important;
	border:1px solid #137332 !important;
	display:inline-block !important;
	cursor:pointer !important;
	color:#ffffff !important;
	font-family:arial !important;
	font-size:13px !important;
	padding:5px 10px !important;
	text-decoration:none !important;
	text-shadow:0px 1px 0px #0c7821 !important;
}
.button-green1:hover {
	background:-webkit-gradient(linear, left top, left bottom, color-stop(0.05, #50a600), color-stop(1, #36bd00)) !important;
	background:-moz-linear-gradient(top, #50a600 5%, #36bd00 100%) !important;
	background:-webkit-linear-gradient(top, #50a600 5%, #36bd00 100%) !important;
	background:-o-linear-gradient(top, #50a600 5%, #36bd00 100%) !important;
	background:-ms-linear-gradient(top, #50a600 5%, #36bd00 100%) !important;
	background:linear-gradient(to bottom, #50a600 5%, #36bd00 100%) !important;
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#50a600', endColorstr='#36bd00',GradientType=0) !important;
	background-color:#50a600 !important;
}
.button-green1:active {
	position:relative !important;
	top:1px !important;
}

.button-yellow1 {
	-moz-box-shadow:inset 0px 1px 0px 0px #f5f558 !important;
	-webkit-box-shadow:inset 0px 1px 0px 0px #f5f558 !important;
	box-shadow:inset 0px 1px 0px 0px #f5f558 !important;
	background:-webkit-gradient(linear, left top, left bottom, color-stop(0.05, #ffd812), color-stop(1, #c9a91c)) !important;
	background:-moz-linear-gradient(top, #ffd812 5%, #c9a91c 100%) !important;
	background:-webkit-linear-gradient(top, #ffd812 5%, #c9a91c 100%) !important;
	background:-o-linear-gradient(top, #ffd812 5%, #c9a91c 100%) !important;
	background:-ms-linear-gradient(top, #ffd812 5%, #c9a91c 100%) !important;
	background:linear-gradient(to bottom, #ffd812 5%, #c9a91c 100%) !important;
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#ffd812', endColorstr='#c9a91c',GradientType=0) !important;
	background-color:#ffd812 !important;
	-moz-border-radius:3px !important;
	-webkit-border-radius:3px !important;
	border-radius:3px !important;
	border:1px solid #736313 !important;
	display:inline-block !important;
	cursor:pointer !important;
	color:#ffffff !important;
	font-family:arial !important;
	font-size:13px !important;
	padding:5px 10px !important;
	text-decoration:none !important;
	text-shadow:0px 1px 0px #78660c !important;
}
.button-yellow1:hover {
	background:-webkit-gradient(linear, left top, left bottom, color-stop(0.05, #c9a91c), color-stop(1, #ffd812)) !important;
	background:-moz-linear-gradient(top, #c9a91c 5%, #ffd812 100%) !important;
	background:-webkit-linear-gradient(top, #c9a91c 5%, #ffd812 100%) !important;
	background:-o-linear-gradient(top, #c9a91c 5%, #ffd812 100%) !important;
	background:-ms-linear-gradient(top, #c9a91c 5%, #ffd812 100%) !important;
	background:linear-gradient(to bottom, #c9a91c 5%, #ffd812 100%) !important;
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#c9a91c', endColorstr='#ffd812',GradientType=0) !important;
	background-color:#c9a91c !important;
}
.button-yellow1:active {
	position:relative !important;
	top:1px !important;
}

.form-control {
	display: block;
	height: 25px;
	padding: 4px 10px;
	font-size: 12px;
	line-height: 1.42857143;
	color: #555;
	background-color: #fff;
	background-image: none;
	border: 1px solid #ccc;
	border-radius: 4px;
	-webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
	box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
	-webkit-transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
	-o-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
	transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
}

.success-box {
	overflow: hidden;
	border-top-left-radius: 0px;
	border-top-right-radius: 0px;
	border-bottom-right-radius: 0px;
	border-bottom-left-radius: 0px;
	border-bottom-width: 2px;
	border-bottom-style: solid;
	border-color: rgb(80, 194, 78);
	border-left-width: 2px;
	border-left-style: solid;
	border-right-width: 2px;
	border-right-style: solid;
	box-shadow: rgba(0, 0, 0, 0.0980392) 0px 2px 4px;
	color: rgb(0, 100, 0);
	background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABsAAAAoCAYAAAAPOoFWAAAAGXRFW…lIN+2qKRyCND0bhqSYCyTB3CAOc4WusBEIpkeBuPgJMAAX8Hs1NfqHRgAAAABJRU5ErkJggg==) 0% 0% repeat-x scroll rgb(144, 238, 144);
}

.warning-box {
	overflow: hidden;
	border-top-left-radius: 0px;
	border-top-right-radius: 0px;
	border-bottom-right-radius: 5px;
	border-bottom-left-radius: 5px;
	border-bottom-width: 2px;
	border-bottom-style: solid;
	border-color: rgb(255, 194, 55);
	border-left-width: 2px;
	border-left-style: solid;
	border-right-width: 2px;
	border-right-style: solid;
	box-shadow: rgba(0, 0, 0, 0.0980392) 0px 2px 4px;
	color: rgb(130, 98, 0);
	background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABsAAAAoCAYAAAAPOoFWAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAPZJREFUeNq81tsOgjAMANB2ov7/7ypaN7IlIwi9rGuT8QSc9EIDAsAznxvY4pXPKr05RUE5MEVB+TyWfCEl9LZApYopCmo9C4FKSMtYoI8Bwv79aQJU4l6hXXCZrQbokJEksxHo9KMOgc6w1atHXM8K9DVC7FQnJ0i8iK3QooGgbnyKgMDygBWyYFZoqx4qS27KqLZJjA1D0jK6QJcYEQEiWv9PGkTsbqxQ8oT+ZtZB6AkdsJnQDnMoHXHLGKOgDYuCWmYhEERCI5gaamW0bnHdA3k2ltlIN+2qKRyCND0bhqSYCyTB3CAOc4WusBEIpkeBuPgJMAAX8Hs1NfqHRgAAAABJRU5ErkJggg==) 0% 0% repeat-x scroll rgb(255, 234, 168) !important;
}

.error-box {
	overflow: hidden;
	border-top-left-radius: 0px;
	border-top-right-radius: 0px;
	border-bottom-right-radius: 0px;
	border-bottom-left-radius: 0px;
	border-bottom-width: 2px;
	border-bottom-style: solid;
	border-color: rgb(139, 0, 0);
	border-left-width: 2px;
	border-left-style: solid;
	border-right-width: 2px;
	border-right-style: solid;
	box-shadow: rgba(0, 0, 0, 0.0980392) 0px 2px 4px;
	color: rgb(255, 255, 255);
	background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABsAAAAoCAYAAAAPOoFWAAAAGXRFW…lIN+2qKRyCND0bhqSYCyTB3CAOc4WusBEIpkeBuPgJMAAX8Hs1NfqHRgAAAABJRU5ErkJggg==) 0% 0% repeat-x scroll red;
}

.alert-box{
	overflow: hidden;
	border-top-left-radius: 0px;
	border-top-right-radius: 0px;
	border-bottom-right-radius: 5px;
	border-bottom-left-radius: 5px;
	border-bottom-width: 2px;
	border-bottom-style: solid;
	border-color: rgb(204, 204, 204);
	border-left-width: 2px;
	border-left-style: solid;
	border-right-width: 2px;
	border-right-style: solid;
	box-shadow: rgba(0, 0, 0, 0.0980392) 0px 2px 4px;
	color: rgb(68, 68, 68);
	background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABsAAAAoCAYAAAAPOoFWAAAAGXRFW…lIN+2qKRyCND0bhqSYCyTB3CAOc4WusBEIpkeBuPgJMAAX8Hs1NfqHRgAAAABJRU5ErkJggg==) 0% 0% repeat-x scroll rgb(255, 255, 255);
}

.info-box{
	overflow: hidden;
	border-top-left-radius: 5px;
	border-top-right-radius: 5px;
	border-bottom-right-radius: 5px;
	border-bottom-left-radius: 5px;
	border: 1px solid rgb(11, 144, 196);
	box-shadow: rgba(0, 0, 0, 0.0980392) 0px 2px 4px;
	color: rgb(255, 255, 255);
	width: 310px;
	background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABsAAAAoCAYAAAAPOoFWAAAAGXRFW…lIN+2qKRyCND0bhqSYCyTB3CAOc4WusBEIpkeBuPgJMAAX8Hs1NfqHRgAAAABJRU5ErkJggg==) 0% 0% repeat-x scroll rgb(87, 183, 226);
}

.error-panel{
	border: 1px solid black;
	color: red;
	padding: 10px;
	margin: 5px;
	display: block; 
	background: #fff;
}

hr.hr-style1{
	height: 2px;
	background: #8e9dbe;
	border: 0;
}

hr.hr-style2{
	height: 3px;
	background: #747e96;
	border: 0;
}